### ISSUE TITLE
Receiving Segmentation Fault After 1/100. Refinement Step

### ISSUE THREAD

**Issue by kilickaya** [satwikkottur/VisualWord2Vec#7]
I successfully conducted all preprocessing steps and compiled the code with it's dependencies. I wanted to try the demo code for visual paraphrasing and run the command line command: 

./bin/visword2vec -vp 1 -embed-path data/vp/word2vec_vp.bin -output vp_refined.bin -size 200 -clusters 100

After Refining 1/100 completes, I receive a segmentation fault and the code halts afterwards. Before halt, I receive this mean Average Precision values: 

mAP: Test (0.944397) Val(0.945528)

Just to let you know that I am on Ubuntu 16.

**Comment by satwikkottur** [comment]
Thanks for pointing this out.
